before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm

cache:
  directories:
    - $HOME/.cache/coursier/v1
    - $HOME/.sbt

dist: xenial

# Don't use -slim or -alpine image tags here - the SBT Wrapper runs a shell script which wouldn't always work then:
env:
  - COMPILE_IMAGE_TAG=8-jdk TEST_IMAGE_TAG=8-jdk
  - COMPILE_IMAGE_TAG=13-jdk TEST_IMAGE_TAG=13-jdk

install:
  - ./docker-sbtx $COMPILE_IMAGE_TAG -batch +test:compile
  - docker-compose up --detach

language: minimal

services:
  # Let's run the build in Docker to protect it from changes in the environment:
  - docker

script: ./docker-sbtx $TEST_IMAGE_TAG -batch +test
