# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the template files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
baseurl: "" # the subpath of your site, e.g. /blog
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
email: your-email@example.com
github_username:  jekyll
title: Your awesome title
twitter_username: jekyllrb
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- node_modules
- package.json
- package-lock.json
- plantuml-loader.js
- README.md
- vendor
- webpack
- webpack.config.js
host: 0.0.0.0
livereload: true
markdown: kramdown
plugins:
- jekyll-feed
