---
services:
  s3:
    command: --compat server /data
    environment:
      MINIO_ACCESS_KEY: Santa-Claus
      MINIO_SECRET_KEY: Ho ho ho
    image: minio/minio:RELEASE.2020-01-16T22-40-29Z
    ports:
      - "12345:9000"

version: "3.7"
